### ISSUE TITLE
errors when from kontiki/python/ run python3 setup.py install 

### ISSUE THREAD

**Issue by icameling** [hovren/kontiki#1]
Hello ~~ Thank you for your excellent work.

I am having some problems compiling the code.

When I from `kontiki/python/` run `sudo python3 setup.py install` ,there is a error as follows

```sh
➜  python git:(master) ✗ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    with open(here / '../README.md') as f:
TypeError: invalid file: PosixPath('../README.md')
```

So I modify the `setup.py`  and delete the code `here /` , here is the code after modifying

```shell
#here = Path(__file__).parents[0]
try:
    #with open('../README.md') as f:
    with open(here / '../README.md') as f:
        long_description = f.read()
except FileNotFoundError:
    long_description = "Omitting long_description since `README.md` is in a parent path."

# Version is defined by C++ library
#with open(here / '../cpplib/CMakeLists.txt') as f:
with open('../cpplib/CMakeLists.txt') as f:
    m = re.search(r'project\(Kontiki VERSION ([\w\.]+)\)', f.read())
    version = m.groups(0)[0]
```

However another error has occurred

```shell
➜  python git:(master) ✗ sudo python3 setup.py install
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to kontiki.egg-info/requires.txt
writing top-level names to kontiki.egg-info/top_level.txt
writing kontiki.egg-info/PKG-INFO
writing dependency_links to kontiki.egg-info/dependency_links.txt
reading manifest file 'kontiki.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'kontiki.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
CMAKE LIST DIR /home/ha/ws_github/kontiki
---------- Running CMake prepare ----------------------------------------
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    'Programming Language :: Python :: 3.6',
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 61, in run
    cwd=self.build_temp, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly
```

Could you give some suggestions ? Thank you a lot !

**Comment by hovren** [comment]
Hi,

It seems like you are using Python 3.5, is that correct?

If so, that is the problem since the minimum supported Python version is 3.6.

**Comment by icameling** [comment]
That's it ! After using Python3.6, I finally compiled the files successfully.  Thank you very much ~

```shell
Installed /usr/local/lib/python3.6/dist-packages/kontiki-0.9-py3.6-linux-x86_64.egg
Processing dependencies for kontiki==0.9
Searching for h5py==2.6.0
Best match: h5py 2.6.0
h5py 2.6.0 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for numpy==1.11.0
Best match: numpy 1.11.0
numpy 1.11.0 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for scipy==0.17.0
Best match: scipy 0.17.0
scipy 0.17.0 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for kontiki==0.9
```


And  by the way, Is there some tutorials or examples like [this](https://github.com/hovren/kontiki_example/blob/master/Kontiki-Example.ipynb) about using Kontiki in the form of C++ without using python? I really appreciate it if you could provide some examples in the form of C++.

**Comment by hovren** [comment]
Glad it worked.

There is currently no C++ tutorial, and I fear I won't have time to make one in the near future.
Feel free to open a new issue about it so that one can track that it has been asked for.

Since the Python API is more or less a direct conversion (i.e. binding) of the C++ classes, you should be able to quite easily take a Python example and do a line-by-line translation to C++.
Note that the C++ API uses `std::shared_ptr` extensively, which means a trajectory is created like this:

`auto trajectory = std::make_shared<kontiki::trajectories::SplitTrajectory>(knot_distance, knot_distance, min_time, min_time);`

**Comment by icameling** [comment]
Thanks for your quick reply. You are a really nice guy. 

I currently focus on the calibration of the LiDAR-IMU system based on a continuous-time trajectory. The Kontiki is a well-written project, and I plan to redevelop it. 

Thanks again for your nice work ~
